using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Fake.DataAccess.Database.CountryData.Migrations
{
    public partial class LanguageTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Languages",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Code = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Languages", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Languages",
                columns: new[] { "Id", "Code" },
                values: new object[,]
                {
                    { 1, "abx" },
                    { 156, "ms-MY" },
                    { 157, "mt" },
                    { 158, "mta" },
                    { 159, "mwl" },
                    { 160, "myv" },
                    { 161, "nb" },
                    { 162, "ne" },
                    { 163, "nkr" },
                    { 164, "nl-BE" },
                    { 165, "nl-NL" },
                    { 166, "nn" },
                    { 167, "no" },
                    { 155, "msb" },
                    { 168, "nog" },
                    { 170, "nrf" },
                    { 171, "nso" },
                    { 172, "oc" },
                    { 173, "or" },
                    { 174, "pa" },
                    { 175, "pag" },
                    { 176, "pam" },
                    { 177, "pau" },
                    { 178, "pl" },
                    { 179, "pon" },
                    { 180, "ps" },
                    { 181, "pt" },
                    { 169, "nr" },
                    { 154, "mrw" },
                    { 153, "mr" },
                    { 152, "mns" },
                    { 125, "it-IT" },
                    { 126, "it-SM" },
                    { 127, "iu" },
                    { 128, "ja" },
                    { 129, "kbd" },
                    { 130, "kl" },
                    { 131, "kn" },
                    { 132, "kok" },
                    { 133, "kos" },
                    { 134, "kpg" },
                    { 135, "krc" },
                    { 136, "krj" },
                    { 137, "ks" },
                    { 138, "ku" },
                    { 139, "kv" },
                    { 140, "la" },
                    { 141, "lb" },
                    { 142, "lt" },
                    { 143, "lus" },
                    { 144, "lv" },
                    { 145, "mdf" },
                    { 146, "mdh" },
                    { 147, "mh" },
                    { 148, "mi" },
                    { 149, "mk" },
                    { 150, "ml" },
                    { 151, "mni" },
                    { 182, "pt-BR" },
                    { 124, "it-CH" },
                    { 183, "pt-PT" },
                    { 185, "rmm" },
                    { 217, "th" },
                    { 218, "tl" },
                    { 219, "tn" },
                    { 220, "to" },
                    { 221, "tox" },
                    { 222, "tr" },
                    { 223, "tr-BG" },
                    { 224, "tr-TR" },
                    { 225, "ts" },
                    { 226, "tsg" },
                    { 227, "tt" },
                    { 228, "tut" },
                    { 216, "tgl" },
                    { 229, "tyv" },
                    { 231, "uk" },
                    { 232, "uli" },
                    { 233, "ur" },
                    { 234, "ur-PK" },
                    { 235, "ve" },
                    { 236, "war" },
                    { 237, "wls" },
                    { 238, "woe" },
                    { 239, "xal" },
                    { 240, "xh" },
                    { 241, "yap" },
                    { 242, "yka" },
                    { 230, "udm" },
                    { 215, "te" },
                    { 214, "ta" },
                    { 213, "sv-SE" },
                    { 186, "ro" },
                    { 187, "rom" },
                    { 188, "ru" },
                    { 189, "ru-UA" },
                    { 190, "sa" },
                    { 191, "sah" },
                    { 192, "sat" },
                    { 193, "sc" },
                    { 194, "sd" },
                    { 195, "se" },
                    { 196, "sgd" },
                    { 197, "sh" },
                    { 198, "si" },
                    { 199, "sit" },
                    { 200, "sk" },
                    { 201, "sl" },
                    { 202, "sm" },
                    { 203, "sma" },
                    { 204, "smn" },
                    { 205, "sov" },
                    { 206, "sq" },
                    { 207, "sr" },
                    { 208, "ss" },
                    { 209, "st" },
                    { 210, "sv" },
                    { 211, "sv-AX" },
                    { 212, "sv-FI" },
                    { 184, "rm" },
                    { 123, "it" },
                    { 122, "is" },
                    { 121, "inh" },
                    { 33, "de" },
                    { 34, "de-AT" },
                    { 35, "de-BE" },
                    { 36, "de-DK" },
                    { 37, "de-CH" },
                    { 38, "de-IT" },
                    { 39, "de-LI" },
                    { 40, "de-LU" },
                    { 41, "diq" },
                    { 42, "doi" },
                    { 43, "en" },
                    { 44, "en-AS" },
                    { 32, "da-GL" },
                    { 45, "en-AU" },
                    { 47, "en-CA" },
                    { 48, "en-FM" },
                    { 49, "en-GB" },
                    { 50, "en-GU" },
                    { 51, "en-IE" },
                    { 52, "en-IN" },
                    { 53, "en-MH" },
                    { 54, "en-MP" },
                    { 55, "en-MT" },
                    { 56, "en-NZ" },
                    { 57, "en-PH" },
                    { 58, "en-PK" },
                    { 46, "en-BM" },
                    { 31, "da-FO" },
                    { 30, "da-DK" },
                    { 29, "da" },
                    { 2, "ady" },
                    { 3, "af" },
                    { 4, "akl" },
                    { 5, "ar-DZ" },
                    { 6, "as" },
                    { 7, "av" },
                    { 8, "az" },
                    { 9, "ba" },
                    { 10, "bcl" },
                    { 11, "be" },
                    { 12, "bg" },
                    { 13, "bh" },
                    { 14, "bik" },
                    { 15, "bn" },
                    { 16, "bn-BD" },
                    { 17, "br" },
                    { 18, "brh" },
                    { 19, "bua" },
                    { 20, "ca" },
                    { 21, "cau" },
                    { 22, "cbk" },
                    { 23, "ce" },
                    { 24, "ceb" },
                    { 25, "co" },
                    { 26, "cs" },
                    { 27, "cv" },
                    { 28, "cy-GB" },
                    { 59, "en-PR" },
                    { 60, "en-PW" },
                    { 61, "en-US" },
                    { 62, "en-VI" },
                    { 94, "fr-PM" },
                    { 95, "fr-RE" },
                    { 96, "fr-WF" },
                    { 97, "fr-YT" },
                    { 98, "fud" },
                    { 99, "fy-NL" },
                    { 100, "gag" },
                    { 101, "ga-IE" },
                    { 102, "gd" },
                    { 103, "gl" },
                    { 104, "gn" },
                    { 105, "gu" },
                    { 106, "gv" },
                    { 107, "haw" },
                    { 108, "hi" },
                    { 109, "hil" },
                    { 110, "hr" },
                    { 111, "hr-HR" },
                    { 112, "hu" },
                    { 113, "hu-HU" },
                    { 114, "ch-GU" },
                    { 115, "chk" },
                    { 116, "chm" },
                    { 117, "ch-MP" },
                    { 118, "ibg" },
                    { 119, "ilo" },
                    { 120, "inc" },
                    { 93, "frp" },
                    { 243, "zh" },
                    { 92, "fr-NC" },
                    { 90, "fr-MC" },
                    { 63, "en-ZA" },
                    { 64, "es" },
                    { 65, "es-AR" },
                    { 66, "es-CO" },
                    { 67, "es-CR" },
                    { 68, "es-DO" },
                    { 69, "es-ES" },
                    { 70, "es-GT" },
                    { 71, "es-MX" },
                    { 72, "es-PR" },
                    { 73, "es-US" },
                    { 74, "es-UY" },
                    { 75, "eu" },
                    { 76, "fi" },
                    { 77, "fi-FI" },
                    { 78, "fil" },
                    { 79, "fi-SE" },
                    { 80, "fo" },
                    { 81, "fr" },
                    { 82, "fr-BE" },
                    { 83, "fr-CA" },
                    { 84, "fr-FR" },
                    { 85, "fr-GF" },
                    { 86, "fr-GP" },
                    { 87, "fr-CH" },
                    { 88, "fr-IT" },
                    { 89, "fr-LU" },
                    { 91, "fr-MQ" },
                    { 244, "zu" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Languages");
        }
    }
}
