// <auto-generated />
using Fake.DataAccess.Database.CountryData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fake.DataAccess.Database.CountryData.Migrations
{
    [DbContext(typeof(CountryDataContext))]
    [Migration("20181019180856_Currency")]
    partial class Currency
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new { Id = 1, Code = "MKD", Name = "Denar" },
                        new { Id = 2, Code = "SEK", Name = "Krona" },
                        new { Id = 3, Code = "EUR", Name = "Euro" },
                        new { Id = 4, Code = "USD", Name = "Dollar" },
                        new { Id = 5, Code = "PHP", Name = "Peso" },
                        new { Id = 6, Code = "NZD", Name = "Dollar" },
                        new { Id = 7, Code = "GBP", Name = "Pound" },
                        new { Id = 8, Code = "XPF", Name = "Franc" },
                        new { Id = 9, Code = "BRL", Name = "Real" },
                        new { Id = 10, Code = "CAD", Name = "Dollar" },
                        new { Id = 11, Code = "HUF", Name = "Forint" },
                        new { Id = 12, Code = "RUB", Name = "Ruble" },
                        new { Id = 13, Code = "MDL", Name = "Leu" },
                        new { Id = 14, Code = "GTQ", Name = "Quetzal" },
                        new { Id = 15, Code = "DKK", Name = "Krone" },
                        new { Id = 16, Code = "BGN", Name = "Lev" },
                        new { Id = 17, Code = "LKR", Name = "Rupee" },
                        new { Id = 18, Code = "BDT", Name = "Taka" },
                        new { Id = 19, Code = "CZK", Name = "Koruna" },
                        new { Id = 20, Code = "DZD", Name = "Dinar" },
                        new { Id = 21, Code = "MYR", Name = "Ringgit" },
                        new { Id = 22, Code = "RON", Name = "Leu" },
                        new { Id = 23, Code = "UYU", Name = "Peso" },
                        new { Id = 24, Code = "ISK", Name = "Krona" },
                        new { Id = 25, Code = "THB", Name = "Baht" },
                        new { Id = 26, Code = "ZAR", Name = "Rand" },
                        new { Id = 27, Code = "MXN", Name = "Peso" },
                        new { Id = 28, Code = "PLN", Name = "Zloty" },
                        new { Id = 29, Code = "COP", Name = "Peso" },
                        new { Id = 30, Code = "CRC", Name = "Colon" },
                        new { Id = 31, Code = "BMD", Name = "Dollar" },
                        new { Id = 32, Code = "DOP", Name = "Peso" },
                        new { Id = 33, Code = "NOK", Name = "Krone" },
                        new { Id = 34, Code = "BYN", Name = "Belarusian ruble" },
                        new { Id = 35, Code = "TRY", Name = "Lira" },
                        new { Id = 36, Code = "AUD", Name = "Dollar" },
                        new { Id = 37, Code = "ARS", Name = "Peso" },
                        new { Id = 38, Code = "JPY", Name = "Yen" },
                        new { Id = 39, Code = "CHF", Name = "Franc" },
                        new { Id = 40, Code = "HRK", Name = "Kuna" },
                        new { Id = 41, Code = "PKR", Name = "Rupee" },
                        new { Id = 42, Code = "UAH", Name = "Hryvnia" },
                        new { Id = 43, Code = "INR", Name = "Rupee" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
