// <auto-generated />
using Fake.DataAccess.Database.CountryData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fake.DataAccess.Database.CountryData.Migrations
{
    [DbContext(typeof(CountryDataContext))]
    [Migration("20181110115346_UniqueIndices")]
    partial class UniqueIndices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<int>("ProvinceId");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Community");
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Area");

                    b.Property<string>("Capital")
                        .IsRequired();

                    b.Property<string>("Continent")
                        .IsRequired();

                    b.Property<int>("CurrencyId");

                    b.Property<string>("Fips");

                    b.Property<string>("Iso")
                        .IsRequired();

                    b.Property<string>("Iso3")
                        .IsRequired();

                    b.Property<int>("IsoNumeric");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhonePrefix")
                        .IsRequired();

                    b.Property<long>("Population");

                    b.Property<string>("PostCodeFormat")
                        .IsRequired();

                    b.Property<string>("PostCodeRegex")
                        .IsRequired();

                    b.Property<string>("TopLevelDomain")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.CountryLanguage", b =>
                {
                    b.Property<int>("CountryId");

                    b.Property<int>("LanguageId");

                    b.HasKey("CountryId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CountryLanguage");
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommunityId");

                    b.Property<string>("LatLong")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PostCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Place");
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<int>("StateId");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("State");
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Community", b =>
                {
                    b.HasOne("Fake.DataAccess.Database.CountryData.Models.Province", "Province")
                        .WithMany("Communities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Country", b =>
                {
                    b.HasOne("Fake.DataAccess.Database.CountryData.Models.Currency", "Currency")
                        .WithMany("Countries")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.CountryLanguage", b =>
                {
                    b.HasOne("Fake.DataAccess.Database.CountryData.Models.Country", "Country")
                        .WithMany("CountryLanguages")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fake.DataAccess.Database.CountryData.Models.Language", "Language")
                        .WithMany("CountryLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Place", b =>
                {
                    b.HasOne("Fake.DataAccess.Database.CountryData.Models.Community", "Community")
                        .WithMany("Places")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.Province", b =>
                {
                    b.HasOne("Fake.DataAccess.Database.CountryData.Models.State", "State")
                        .WithMany("Provinces")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fake.DataAccess.Database.CountryData.Models.State", b =>
                {
                    b.HasOne("Fake.DataAccess.Database.CountryData.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
